collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.9704618
color:
  saturation: 0.744898
  brandStrength: 0.4989259
  lightness: 1
  brandColors:
    - '#160118'
    - '#FDF2AB'
    - '#FDFA2F'
    - '#6E91A3'
    - '#9A0320'
  rhythmicContrast: 0.6503759
layout_spectrum: 1
name: GraceTruthWords
