layout_spectrum: 1
typography_spectrum: 0.9704618
color:
  saturation: 0.5171858
  lightness: 0.9092373
  brandStrength: 0.9864967
  rhythmicContrast: 0.5397422
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: GraceTruthWords
